import { IndiaStateInfo, DataSourceItem, RegenerativeStrategy, CropDiseaseResult } from '../types';

export const INDIAN_STATES: Record<string, IndiaStateInfo> = {
  'Uttar Pradesh': {
    id: 'UP',
    name: 'Uttar Pradesh',
    hindiName: 'उत्तर प्रदेश',
    majorCrops: ['Wheat', 'Rice', 'Sugarcane', 'Potato', 'Mustard'],
    climateRisk: 'MEDIUM',
    diseaseRisk: 'LOW',
    cropHealth: 82,
    rainfall: 'Normal',
    soilMoisture: 64,
    ndvi: 0.74,
    waterStress: 'Moderate',
    sharedModels: ['Gangetic Plain Soil Carbon Ledger', 'Sugarcane Drip Protocol'],
    activeFarmers: 1420500,
    advisoriesIssued: 489210,
    coordinates: { x: 48, y: 38 },
  },
  'Punjab': {
    id: 'PB',
    name: 'Punjab',
    hindiName: 'पंजाब',
    majorCrops: ['Wheat', 'Rice', 'Cotton', 'Maize'],
    climateRisk: 'HIGH',
    diseaseRisk: 'MEDIUM',
    cropHealth: 78,
    rainfall: 'Deficit (-12%)',
    soilMoisture: 52,
    ndvi: 0.71,
    waterStress: 'High',
    sharedModels: ['Direct Seeded Rice (DSR) Water Optimizer', 'Happy Seeder Straw Protocol'],
    activeFarmers: 890400,
    advisoriesIssued: 395120,
    coordinates: { x: 32, y: 26 },
  },
  'Maharashtra': {
    id: 'MH',
    name: 'Maharashtra',
    hindiName: 'महाराष्ट्र',
    majorCrops: ['Cotton', 'Sugarcane', 'Soybean', 'Pulses', 'Onion'],
    climateRisk: 'HIGH',
    diseaseRisk: 'LOW',
    cropHealth: 75,
    rainfall: 'Normal (+4%)',
    soilMoisture: 58,
    ndvi: 0.68,
    waterStress: 'High',
    sharedModels: ['Vidarbha Micro-Catchment Water Ledger', 'Black Soil Moisture Retainer'],
    activeFarmers: 1650000,
    advisoriesIssued: 562300,
    coordinates: { x: 38, y: 58 },
  },
  'Madhya Pradesh': {
    id: 'MP',
    name: 'Madhya Pradesh',
    hindiName: 'मध्य प्रदेश',
    majorCrops: ['Soybean', 'Wheat', 'Gram', 'Maize', 'Mustard'],
    climateRisk: 'MEDIUM',
    diseaseRisk: 'LOW',
    cropHealth: 84,
    rainfall: 'Normal',
    soilMoisture: 62,
    ndvi: 0.76,
    waterStress: 'Moderate',
    sharedModels: ['Pulse-based Nitrogen Fixation Tracker', 'Organic Soya Certification Hub'],
    activeFarmers: 1210000,
    advisoriesIssued: 412000,
    coordinates: { x: 44, y: 48 },
  },
  'Bihar': {
    id: 'BR',
    name: 'Bihar',
    hindiName: 'बिहार',
    majorCrops: ['Rice', 'Wheat', 'Maize', 'Pulses', 'Jute'],
    climateRisk: 'HIGH',
    diseaseRisk: 'MEDIUM',
    cropHealth: 76,
    rainfall: 'Excess (+18%)',
    soilMoisture: 72,
    ndvi: 0.69,
    waterStress: 'Low',
    sharedModels: ['Kosi Basin Flood Inundation Matrix', 'Makhana Precision Water Tracker'],
    activeFarmers: 980000,
    advisoriesIssued: 310500,
    coordinates: { x: 64, y: 40 },
  },
  'Rajasthan': {
    id: 'RJ',
    name: 'Rajasthan',
    hindiName: 'राजस्थान',
    majorCrops: ['Mustard', 'Bajra (Millets)', 'Wheat', 'Guar', 'Gram'],
    climateRisk: 'CRITICAL',
    diseaseRisk: 'LOW',
    cropHealth: 68,
    rainfall: 'Deficit (-22%)',
    soilMoisture: 38,
    ndvi: 0.54,
    waterStress: 'Severe',
    sharedModels: ['Arid Agro-Forestry Khejri Framework', 'Solar Drip Irrigation Balancing'],
    activeFarmers: 780000,
    advisoriesIssued: 284000,
    coordinates: { x: 26, y: 36 },
  },
  'Tamil Nadu': {
    id: 'TN',
    name: 'Tamil Nadu',
    hindiName: 'तमिलनाडु',
    majorCrops: ['Rice', 'Groundnut', 'Millets', 'Sugarcane', 'Cotton'],
    climateRisk: 'MEDIUM',
    diseaseRisk: 'MEDIUM',
    cropHealth: 86,
    rainfall: 'Normal (+8%)',
    soilMoisture: 66,
    ndvi: 0.81,
    waterStress: 'Moderate',
    sharedModels: ['Cauvery Delta Salinity Early Warning', 'System of Rice Intensification (SRI) Model'],
    activeFarmers: 890000,
    advisoriesIssued: 341000,
    coordinates: { x: 42, y: 82 },
  },
  'Karnataka': {
    id: 'KA',
    name: 'Karnataka',
    hindiName: 'कर्नाटक',
    majorCrops: ['Ragi (Millets)', 'Rice', 'Maize', 'Coffee', 'Cotton'],
    climateRisk: 'MEDIUM',
    diseaseRisk: 'LOW',
    cropHealth: 81,
    rainfall: 'Normal',
    soilMoisture: 60,
    ndvi: 0.77,
    waterStress: 'Moderate',
    sharedModels: ['Deccan Millets Drought Shield', 'Soil Health Card Automated Prescription'],
    activeFarmers: 920000,
    advisoriesIssued: 360000,
    coordinates: { x: 36, y: 72 },
  },
};

export const DISTRICTS_BY_STATE: Record<string, string[]> = {
  'Uttar Pradesh': ['Prayagraj', 'Varanasi', 'Lucknow', 'Gorakhpur', 'Kanpur', 'Agra', 'Meerut', 'Ayodhya'],
  'Punjab': ['Ludhiana', 'Amritsar', 'Patiala', 'Bathinda', 'Jalandhar', 'Firozpur'],
  'Maharashtra': ['Nagpur', 'Nashik', 'Pune', 'Aurangabad', 'Solapur', 'Kolhapur', 'Amravati'],
  'Madhya Pradesh': ['Bhopal', 'Indore', 'Jabalpur', 'Ujjain', 'Gwalior', 'Sagar', 'Hoshangabad'],
  'Bihar': ['Patna', 'Gaya', 'Muzaffarpur', 'Bhagalpur', 'Purnia', 'Darbhanga'],
  'Rajasthan': ['Jaipur', 'Jodhpur', 'Bikaner', 'Kota', 'Udaipur', 'Alwar', 'Sri Ganganagar'],
  'Tamil Nadu': ['Thanjavur', 'Madurai', 'Coimbatore', 'Tiruchirappalli', 'Salem', 'Tirunelveli'],
  'Karnataka': ['Mandya', 'Mysuru', 'Belagavi', 'Dharwad', 'Shimoga', 'Tumakuru', 'Ballari'],
};

export const CROPS_CONFIG: Record<string, {
  varieties: string[];
  stages: string[];
  soilSuitability: string[];
  icon: string;
  season: 'Rabi' | 'Kharif' | 'Zaid' | 'Annual';
}> = {
  Wheat: {
    varieties: ['HD-2967', 'HD-3086 (Pusa Gautami)', 'PBW-550', 'DBW-187 (Karan Vandana)', 'Sharbati'],
    stages: ['Crown Root Initiation (21-25 DAS)', 'Tillering (40-45 DAS)', 'Jointing', 'Flowering / Booting', 'Milking / Grain Filling', 'Maturity & Harvesting'],
    soilSuitability: ['Alluvial Loam', 'Clay Loam', 'Sandy Loam'],
    icon: '🌾',
    season: 'Rabi',
  },
  Rice: {
    varieties: ['Pusa Basmati 1121', 'Pusa Basmati 1509', 'Swarna (MTU 7029)', 'IR 64', 'PR 126'],
    stages: ['Nursery / Seedling', 'Transplanting / Tillering', 'Panicle Initiation', 'Flowering', 'Dough Stage', 'Harvest'],
    soilSuitability: ['Clayey', 'Clay Loam', 'Silty Alluvium'],
    icon: '🌾',
    season: 'Kharif',
  },
  Maize: {
    varieties: ['Pioneer P3396', 'NK 6240', 'DHM 117', 'Dekalb 9108', 'Ganga 11'],
    stages: ['Emergence (VE-V2)', 'Knee-high (V6-V8)', 'Tasseling (VT)', 'Silking (R1)', 'Dent / Dough', 'Physiological Maturity'],
    soilSuitability: ['Deep Loam', 'Sandy Loam', 'Well-drained Alluvial'],
    icon: '🌽',
    season: 'Kharif',
  },
  Cotton: {
    varieties: ['Bt Cotton RCH 659', 'Bollgard II', 'Ankur 3028', 'MRC 7017', 'Suraj'],
    stages: ['Squaring', 'Flowering & Boll formation', 'Boll maturation', 'Bursting & Picking'],
    soilSuitability: ['Deep Black Soil (Regur)', 'Medium Black Soil', 'Alluvial'],
    icon: '☁️',
    season: 'Kharif',
  },
  Sugarcane: {
    varieties: ['Co 0238 (Karan 4)', 'CoLk 94184', 'Co 86032', 'Co 11015'],
    stages: ['Germination', 'Formative / Tillering', 'Grand Growth', 'Ripening'],
    soilSuitability: ['Deep Loamy Soil', 'Heavy Alluvium'],
    icon: '🎋',
    season: 'Annual',
  },
  Pulses: {
    varieties: ['Gram Pusa 362', 'Arhar Pusa 992', 'Moong Virat', 'Urad PU 31'],
    stages: ['Vegetative Growth', 'Branching', 'Pod Formation', 'Pod Filling', 'Maturity'],
    soilSuitability: ['Sandy Loam', 'Medium Loam', 'Well-drained Black'],
    icon: '🫘',
    season: 'Rabi',
  },
  Millets: {
    varieties: ['Bajra MPMH 17', 'Ragi GPU 28', 'Jowar CSH 25', 'Foxtail Millet Kangni'],
    stages: ['Seedling', 'Tillering', 'Flag Leaf / Panicle', 'Grain Setting', 'Maturity'],
    soilSuitability: ['Sandy Loam', 'Red Soil', 'Shallow Black'],
    icon: '🌾',
    season: 'Kharif',
  },
};

export const SAMPLE_CROP_DISEASES: CropDiseaseResult[] = [
  {
    id: 'wheat-rust',
    disease: 'Wheat Yellow / Stripe Rust (Puccinia striiformis)',
    scientificName: 'Puccinia striiformis f. sp. tritici',
    confidence: 94,
    riskLevel: 'HIGH',
    observedSymptoms: [
      'Linear yellow-orange stripes of uredinial pustules along the leaf veins',
      'Chlorotic stippling transitioning to powdery fungal spores',
      'Premature desiccation of upper flag leaves reducing photosynthate allocation'
    ],
    recommendedNextSteps: [
      'Immediately isolate infected field patches to prevent downwind spore dispersal',
      'Withhold nitrogenous fertilizer top-dressing which exacerbates fungal vegetative spread',
      'Schedule fungicide spray within 24-48 hours before boot stage'
    ],
    prevention: [
      'Adopt resistant wheat varieties such as DBW-187 and DBW-222 in future cycles',
      'Conduct regular strip-scouting in humid early morning conditions',
      'Avoid high-density seed broadcasting to allow air circulation'
    ],
    organicRemedy: 'Foliar spray of 5% Neem Seed Kernel Extract (NSKE) blended with Trichoderma viride (10g/L).',
    chemicalRemedy: 'Propiconazole 25% EC @ 1ml/L or Tebuconazole 25.9% EC @ 1.25ml/L with fine droplet mist.',
    expertDisclaimer: 'AI-assisted screening based on Gemini Vision pattern analysis. Confirm with your nearest Krishi Vigyan Kendra (KVK) officer.',
    isDemo: true,
    analyzedAt: new Date().toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'rice-blight',
    disease: 'Bacterial Leaf Blight of Rice (Xanthomonas oryzae)',
    scientificName: 'Xanthomonas oryzae pv. oryzae',
    confidence: 91,
    riskLevel: 'HIGH',
    observedSymptoms: [
      'Water-soaked to yellowish-white wavy lesions along leaf margins',
      'Milky bacterial ooze droplets visible on cut leaf tips during humid mornings',
      'Kresek symptom (wilting of young tillers) in localized low-drainage sections'
    ],
    recommendedNextSteps: [
      'Drain stagnant standing water from paddy basins for 48 hours to expose soil surface',
      'Suspend split application of Urea; supplement with Muriate of Potash (MOP) to harden cell walls',
      'Sanitize farm implements moving between affected and healthy plots'
    ],
    prevention: [
      'Use certified disease-free foundation seed treated with Streptocycline',
      'Implement alternate wetting and drying (AWD) water management',
      'Eradicate collateral weed hosts such as Cyperus and Leersia along irrigation bunds'
    ],
    organicRemedy: 'Cow urine + Asafoetida (Hing) microbial wash spray @ 10% dilution.',
    chemicalRemedy: 'Streptocycline (1.5g) + Copper Oxychloride 50% WP (25g) in 10 Litres of clean water.',
    expertDisclaimer: 'AI-assisted screening based on Gemini Vision pattern analysis. Confirm with your nearest Krishi Vigyan Kendra (KVK) officer.',
    isDemo: true,
    analyzedAt: new Date().toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1530595467537-0b5996c41f2d?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'cotton-curl',
    disease: 'Cotton Leaf Curl Virus (CLCuV)',
    scientificName: 'Begomovirus / Geminiviridae',
    confidence: 89,
    riskLevel: 'MEDIUM',
    observedSymptoms: [
      'Upward and downward curling of young apical leaves with thickened main veins',
      'Enation (leaf-like outgrowths) on the abaxial side of the leaf',
      'Stunting of plant height and abortion of early floral squares'
    ],
    recommendedNextSteps: [
      'Control whitefly vector populations (Bemisia tabaci) which transmit the virion',
      'Install yellow sticky traps @ 12-15 traps per acre to monitor vector density',
      'Rogue out severely deformed early-stage plants to halt secondary transmission'
    ],
    prevention: [
      'Plant border barrier crops (2-3 rows of pearl millet / maize / sorghum)',
      'Sow recommended virus-tolerant Bt hybrids certified for northern/central zones',
      'Refrain from excessive late vegetative irrigation'
    ],
    organicRemedy: 'Neem Oil 10,000 ppm @ 2.5ml/L + Pongamia oil emulsion to disrupt whitefly feeding.',
    chemicalRemedy: 'Diafenthiuron 50% WP @ 1.2g/L or Pyriproxyfen 10% EC @ 2ml/L.',
    expertDisclaimer: 'AI-assisted screening based on Gemini Vision pattern analysis. Confirm with your nearest Krishi Vigyan Kendra (KVK) officer.',
    isDemo: true,
    analyzedAt: new Date().toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1605000797499-95a51c5269ae?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'tomato-early-blight',
    disease: 'Tomato Early Blight (Alternaria solani)',
    scientificName: 'Alternaria solani',
    confidence: 96,
    riskLevel: 'MEDIUM',
    observedSymptoms: [
      'Concentric target-like dark brown rings on older lower leaves',
      'Yellow chlorotic halos surrounding lesions leading to defoliation',
      'Sunscald on exposed developing fruit due to canopy leaf loss'
    ],
    recommendedNextSteps: [
      'Prune lowest leaves touching the moist soil bed to break splash-dispersal cycle',
      'Switch from overhead sprinkler irrigation to root-zone drip lines',
      'Apply organic mulch (straw or dried grass) around the plant base'
    ],
    prevention: [
      'Practice minimum 3-year crop rotation avoiding Solanaceous relatives (potato, brinjal)',
      'Ensure 60cm plant-to-plant spacing for uniform ventilation',
      'Disinfect staking bamboo posts before reuse'
    ],
    organicRemedy: 'Foliar bio-fungicide Bacillus subtilis @ 5g/L combined with Panchagavya 3% solution.',
    chemicalRemedy: 'Mancozeb 75% WP @ 2.5g/L or Azoxystrobin 23% SC @ 1ml/L.',
    expertDisclaimer: 'AI-assisted screening based on Gemini Vision pattern analysis. Confirm with your nearest Krishi Vigyan Kendra (KVK) officer.',
    isDemo: true,
    analyzedAt: new Date().toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1592417817098-8f3d6910985c?auto=format&fit=crop&w=600&q=80',
  }
];

export const REGENERATIVE_PRACTICES: RegenerativeStrategy[] = [
  {
    practice: 'Crop Rotation with Legumes',
    hindiPractice: 'दलहनी फसलों के साथ फसल चक्र',
    icon: '🔄',
    what: 'Rotating cereal crops (Wheat, Rice) with short-duration nitrogen-fixing legumes (Chickpea, Moong, Lentil).',
    why: 'Legume root nodules harbor symbiotic Rhizobium bacteria that convert atmospheric N2 into plant-available nitrates.',
    expectedBenefit: 'Reduces synthetic urea requirements by 25-35 kg/acre, enhances soil organic carbon, and breaks cereal weed cycles.',
    costEfficiency: 'Saves ₹1,200 - ₹1,800/acre in fertilizer inputs while delivering secondary pulse harvest.',
    difficulty: 'Easy',
  },
  {
    practice: 'Bio-Mulching & Zero Residue Burning',
    hindiPractice: 'जैव-मल्चिंग एवं अवशेष प्रबंधन',
    icon: '🍂',
    what: 'Retaining crop stubble and straw on the soil surface using Happy Seeders / Super Seeders without burning.',
    why: 'Stubble mulch cools the soil surface by 3-5°C during early summer heat waves and conserves soil capillary moisture.',
    expectedBenefit: 'Retains 40-50% more root moisture, eliminates winter smog, and elevates organic carbon by 0.15% per 3 seasons.',
    costEfficiency: 'Lowers irrigation frequency by 2 cycles, saving ₹900/acre in pumping diesel/electricity.',
    difficulty: 'Moderate',
  },
  {
    practice: 'Multi-Species Cover Cropping',
    hindiPractice: 'बहु-प्रजाति आवरण फसलें',
    icon: '🌱',
    what: 'Sowing a fast-growing companion blend (Dhaincha, Sunnhemp, Mustard) during the post-harvest fallow window.',
    why: 'Continuous live root networks nourish beneficial mycorrhizal fungi and prevent monsoonal topsoil erosion.',
    expectedBenefit: 'Suppresses invasive weeds by 70%, captures residual nitrates, and contributes 12-15 tonnes of green manure biomass.',
    costEfficiency: 'Generates organic in-situ fertilizer worth ~₹2,500/acre at minimal seed investment.',
    difficulty: 'Easy',
  },
  {
    practice: 'Conservation Tillage (Minimum Tillage)',
    hindiPractice: 'संरक्षित जुताई (न्यूनतम जुताई)',
    icon: '🚜',
    what: 'Restricting soil inversion and deep plowing, preparing seedbeds in a single zero-till pass.',
    why: 'Aggressive rotary plowing pulverizes soil aggregates, oxidizes humus, and disrupts natural earthworm burrows.',
    expectedBenefit: 'Preserves delicate soil pore architecture, improves rain infiltration by 30%, and drastically reduces tractor diesel use.',
    costEfficiency: 'Saves 15-20 liters of tractor diesel per acre (~₹1,500/acre operational savings).',
    difficulty: 'Moderate',
  },
  {
    practice: 'Biochar & Compost Enriched Carbon',
    hindiPractice: 'बायोचार एवं समृद्ध कम्पोस्ट',
    icon: '🪵',
    what: 'Incorporating pyrolyzed agricultural biomass (biochar) alongside vermicompost and Trichoderma cultures.',
    why: 'Biochar provides a highly porous, recalcitrant carbon lattice that holds nutrients and beneficial microbes for decades.',
    expectedBenefit: 'Doubles cation exchange capacity (CEC), neutralizes soil pH swings, and creates drought-resilient sponge soil.',
    costEfficiency: 'Long-term yield stabilization against heat-waves, reducing crop failure insurance risk.',
    difficulty: 'Advanced',
  },
  {
    practice: 'Precision Sub-surface & Drip Irrigation',
    hindiPractice: 'सटीक ड्रिप एवं सूक्ष्म सिंचाई',
    icon: '💧',
    what: 'Delivering micro-doses of water and water-soluble bio-stimulants directly to the root zone under low pressure.',
    why: 'Flood irrigation loses 45-60% of water to deep percolation and evaporation while leaching nitrates into groundwater.',
    expectedBenefit: 'Conserves 50-65% irrigation water while boosting fertilizer use efficiency (FUE) by 40%.',
    costEfficiency: 'Eligible for 70-80% state subsidies under PM Krishi Sinchayee Yojana (PMKSY).',
    difficulty: 'Moderate',
  },
  {
    practice: 'Agro-Forestry & Pollinator Field Borders',
    hindiPractice: 'कृषि-वानिकी एवं परागण पट्टी',
    icon: '🐝',
    what: 'Planting indigenous flowering shrubs, marigolds, and native trees (Neem, Khejri, Subabul) along boundary bunds.',
    why: 'Attracts natural predatory insects (ladybirds, hoverflies) and native bees while acting as windbreaks against lodging.',
    expectedBenefit: 'Increases cross-pollination fruit-set by 18-22% and slashes synthetic pesticide reliance by half.',
    costEfficiency: 'Yields timber, firewood, and honey revenue streams alongside core agronomy.',
    difficulty: 'Easy',
  },
];

export const DATA_SOURCES: DataSourceItem[] = [
  {
    id: 'ds-imd',
    name: 'India Meteorological Department (IMD) / Mausam',
    category: 'Weather',
    provider: 'Ministry of Earth Sciences, Govt of India',
    type: 'LIVE API',
    status: 'Operational',
    updateFrequency: 'Every 3 Hours',
    description: 'Real-time gridded weather observations, district agro-met bulletins, radar precipitation scans, and 7-day numerical weather predictions.',
    endpointOrSource: 'https://mausam.imd.gov.in/ (Augmented with Open-Meteo High-Resolution Grids)',
  },
  {
    id: 'ds-shc',
    name: 'Soil Health Card Scheme (SHC) & ICAR',
    category: 'Soil',
    provider: 'Ministry of Agriculture & Farmers Welfare / ICAR',
    type: 'PUBLIC DATASET',
    status: 'Public Open Data',
    updateFrequency: 'Bi-annual Cycle',
    description: 'Geo-referenced soil test results across Indian districts: pH, EC, Organic Carbon, Nitrogen, Phosphorus, Potassium, Zinc, and Boron benchmarks.',
    endpointOrSource: 'https://soilhealth.dac.gov.in/ (Geo-tagged district soil benchmark repository)',
  },
  {
    id: 'ds-bhuvan',
    name: 'ISRO Bhuvan & Copernicus Sentinel-2',
    category: 'Satellite',
    provider: 'ISRO National Remote Sensing Centre (NRSC) / ESA',
    type: 'PUBLIC DATASET',
    status: 'Public Open Data',
    updateFrequency: '5-Day Revisit Interval',
    description: '10m multi-spectral satellite imagery delivering Normalized Difference Vegetation Index (NDVI), Moisture Stress Index, and flood water inundation masks.',
    endpointOrSource: 'https://bhuvan.nrsc.gov.in/ (10m Multispectral Bands B4, B8, B11)',
  },
  {
    id: 'ds-gemini',
    name: 'Google Gemini 1.5 Pro / Flash Model',
    category: 'Crop Health',
    provider: 'Google AI / DeepMind',
    type: 'LIVE API',
    status: 'Operational',
    updateFrequency: 'Real-time Multi-modal Inference',
    description: 'High-reasoning agronomical synthesis engine combining multi-tier spatial vectors with localized agricultural knowledge for structured farmer advisories.',
    endpointOrSource: 'Google Generative AI SDK (@google/generative-ai) via Server-side Proxy',
  },
  {
    id: 'ds-agmarknet',
    name: 'AGMARKNET Mandi Price Intelligence',
    category: 'Market / Mandi',
    provider: 'Directorate of Marketing & Inspection (DMI)',
    type: 'LIVE API',
    status: 'Operational',
    updateFrequency: 'Daily Real-time',
    description: 'Live APMC market arrivals, minimum, maximum, and modal wholesale agricultural commodity prices across 2,800+ Indian mandis.',
    endpointOrSource: 'https://agmarknet.gov.in/ (National Agriculture Market Data Hub)',
  },
  {
    id: 'ds-demo-telemetry',
    name: 'Krishi State Federation Demo Telemetry',
    category: 'Climate Risk',
    provider: 'Digital Agriculture Sandbox Engine',
    type: 'DEMO DATA',
    status: 'Simulated',
    updateFrequency: 'Continuous Simulation',
    description: 'Consistent synthetic telemetry for multi-state knowledge exchange, edge cases, and hackathon presentation reliability.',
    endpointOrSource: 'Krishi Intelligence Localized Simulation Service',
  },
];
